# AzuraCast Docs build process
# Powered by Netlify

[build]
  publish = "dist"
  command = "npm run build"

[[plugins]]
package = "netlify-plugin-checklinks"
  [plugins.inputs]
  pretty = true
